from __future__ import annotations

from enum import Enum


class EventType(str, Enum):
    UNSUPERVISED_DETECTED = "UNSUPERVISED_DETECTED"
    ALERT_CREATED = "ALERT_CREATED"
    ALERT_ACKNOWLEDGED = "ALERT_ACKNOWLEDGED"
    ALERT_RESOLVED = "ALERT_RESOLVED"
    BUZZER_TRIGGERED = "BUZZER_TRIGGERED"
    BUZZER_CLEARED = "BUZZER_CLEARED"
    ADULT_RETURNED = "ADULT_RETURNED"
    SUPERVISION_RESTORED = "SUPERVISION_RESTORED"  # internal signal consumed by AlertManager to resolve an alert
    CAMERA_OFFLINE = "CAMERA_OFFLINE"
    CAMERA_ONLINE = "CAMERA_ONLINE"
    CLASSROOM_STATUS_CHANGED = "CLASSROOM_STATUS_CHANGED"
    TRACKED_STATE_UPDATE = "TRACKED_STATE_UPDATE"  # per-frame debug/live overlay payload
